apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testnodejs0325a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testnodejs0325a 
  name: testnodejs0325a
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: testnodejs0325a 
